### ISSUE TITLE
concretizes definition too restricted

### ISSUE THREAD

**Issue by neilotte** [BFO-ontology/BFO-2020#17]
The definition of _concretizes at all times_ in bfo-2020.ttl states:

"an s-dependent continuant b concretizes a g-dependent continuant c at all times =Def for all times t, b exists at t implies (c is the pattern or content which b shares at t with actual or potential copies)"

From this definition, one would understand the domain to be SDC and the range GDC.

However, the domain in OWL is restricted to SDC or Process. 

Hence, the definition needs to be expanded to allow 'b' to be a process and specify the conditions under which a process can concretize a GDC. 

The same holds for _concretizes at some times_ .

**Comment by alanruttenberg** [comment]
I agree. Hasn't been done because Barry only reluctantly agreed to concretization as processes (despite inspiration Ingarden  talking about this). I think it was an oversight and I'm not sure we have a candidate definition.

There's this thing about g-depends-on that it is to the independent continuant bearers of the concretizations. It doesn't include processes because they aren't ICs. I'm not fond of that as I don't see the g-depends-on relationship as useful given that we have the concretization relationship that carries the same or more (in the case of processes) information. But I think it's the same issue.

Not sure what to do. Want to offer a revised definition?

**Comment by neilotte** [comment]
Makes sense. 

Nailing this down invites bringing in more language than is defined within BFO. So I suppose the trick is to do it without bringing in too much by way of undefined fluff. I'm assuming only directives can be concretized in processes, and even then only when the goal(s) declared in the directive are realized in the process, but I've been out of the loop on these conversations. (On this issue, I'd wonder how this useage holds up against cco:prescribes). 

Assuming the above is correct, here's a candidate: 

"an s-dependent continuant or process b concretizes a g-dependent continuant c at all times =Def for all times t, b exists at t implies that: i) if b instanceOf s-dependent continuant, then c is the pattern or content which b shares at t with actual or potential copies) and ii) if b instance-of process, then c is the g-dependent continuant that _guides, prescribes, directs, or specifies_ [pick one of the aforementioned verbs] b."

Maybe some of this could be unpacked with an elucidation to the effect that only GDCs that are directives, such as plans, with a mind-to-world fit may serve in the domain, and only achievements (processes with a necessarily identified end state) may serve in the range, and that the relation between them only then holds when the GDC guides, prescribes, directs, or specifies the achievement. 

Thoughts?

**Comment by alanruttenberg** [comment]
So, the case I was thinking about wasn't goal-seeking process but rather communication/performance processes. For example a message is communicated by flag semaphore, or a poem is read in an in a society with an oral tradition, or a message is sent by radio to mars. 

In some of these cases there isn't necessarily concretizations other than in the brain of the performer, and what needs to be explained is how a concretization lands up on the receiving side.

An extreme but not implausible story that illustrates the necessity: A radio transmission is sent to mars. While en route the sender explodes. But the radio waves continue to propagate (a process) even though the sender has been blown up. If the only concretizations were in the sender and perhaps a sheet of paper from which the sender is reading, then what carries the GDC in the period after the sender has blown up, and before it is received on mars?

Taken to the limit it's a reasonable question as to whether all communication processes / performances are concretizations. I'm not sure but it seems that at least some are.

In the case you are talking about the story is that the directive information entity is concretized as a realizable entity (read plan) and the process described in your comment is the realization of that concretization. 

The way I'm thinking about it, concretizations can be of any kind of information entity. An alternative to (ii) is

>if b instance-of a process, then b is a communication or performance of the information content of c

However, both of our definitions may suffer from the same problem namely that they imply that they describe not GDCs in general, but ICEs. In mine it's explicit. In yours it is implied there's a directive in the story, and those are ICEs.

Ideally the definition of the GDC wouldn't be defined by reference, in part, to a subclass that isn't part of BFO. Here's one try:

> ii) if b instance-of process then b unfolds according to the pattern or content which b shares at t with actual or potential copies and is sufficient to enable another concretization of c to come into existence.

**Comment by neilotte** [comment]
Wow @alanruttenberg , I was way off. Ok, so some questions.

1. I can't make heads or tails of the temporal versions of the concretizes relation then. If P (a process) concretizes at some time I (a GDC), then what does that mean and when is that true? Ditto for concretizes at all times. 

2. To your story about the radio waves: I recognize that there is a process occurring as the radio waves propagate. I'm a little incredulous that we can't identify the something that carries the GDC in the period after the sender has blown up, and before it is received on Mars. Couldn't we just say that fiat portions of an electro-magnetic field carry the information? Or, alternatively, that chains of protons, at any given time during the transmission, are the carriers of the transmission? I don't know why Barry's typical party line seems to be flagging here regarding the sound waves of the orator being the bearer of the communication and what not.

**Comment by alanruttenberg** [comment]
1. I think that the concretization needs to exist for the whole of the process. But you make a good point. all-times implies some-time, but not vice versa. Perhaps there should be an axiom that if process p concretizes as some time , then it concretizes at all times. Or maybe there should be an atemporal concretization relationship. I'd probably lean to the former. There's precedent. For example parts of spatial regions can only be part at all times, and the parthood is rigid. A spatial region can't be part of two disjoint spatial regions at different times.

2. We don't have a story about fields. They are difficult because in some cases they are dependent on a bearer, but at other times they are self-sufficient (no ether an all that). So are they independent continuant or specifically dependent continuant? If they are independent continuants, then how can they carry a concretization at all (that's the job of SDCs or processes). If they are specifically dependent continuants, what do they depend on? Remember, if whatever they s-depend-on ceases to exist then they also cease to exist. 

I don't buy Barry's story. The sound molecules keep getting used over and over again for different parts of the communication. In the typical case of two people talking there's no point in time where all of the message is borne by some aggregate of molecules.

**Comment by alanruttenberg** [comment]
Barry is fine with this definition. He'll have to change it in the spec, and I will get it into the OWL.

An s-dependent continuant or process b concretizes a g-dependent continuant c at all times =Def for all times t, b exists at t implies that: i) if b instanceOf s-dependent continuant, then c is the pattern or content which b shares at t with actual or potential copies) and ii)  if b instance-of process then b unfolds according to the pattern or content which b shares at t with actual or potential copies and is sufficient to enable another concretization of c to come into existence.

**Comment by alanruttenberg** [comment]
>1. I can't make heads or tails of the temporal versions of the concretizes relation then. If P (a process) concretizes at some time I (a GDC), then what does that mean and when is that true? Ditto for concretizes at all times.

Process concretizes at some time: 
- A message is encoded by laser heading out towards a satellite. Along the way it goes through the tail of a comet and get dispersed and the message becomes unrecoverable.
- The radio communications between a mobile phone and a tower is interrupted by a signal jammer.

Process concretizes at all times:
- A message is initiated and received at the end of a fiber optic cable, the received designed not to reflect. In this case on reception the light energy is transduced to another form of energy, e.g. electric current.
- A play is performed in a room with walls that absorb sound (e.g. so as not to disturb or be interrupted by outside noise).

>2. To your story about the radio waves: I recognize that there is a process occurring as the radio waves propagate. I'm a little incredulous that we can't identify the something that carries the GDC in the period after the sender has blown up, and before it is received on Mars. 

Talk to Einstein. https://en.wikipedia.org/wiki/Luminiferous_aether . Physics does not respect intuition. 

>Couldn't we just say that fiat portions of an electro-magnetic field carry the information? 

A propagating electro-magnetic field is a wave. It has a frequency. Things that have a frequency are processes.

>Or, alternatively, that chains of protons, at any given time during the transmission, are the carriers of the transmission? 

Maybe there are some physical systems where this is the case, but ... empty space, no aether ...

>I don't know why Barry's typical party line seems to be flagging here regarding the sound waves of the orator being the bearer of the communication and what not.

Sound waves are are easier to grab on to because they are conveyed by pressure and pressure is related to the kinetic energy of atoms/molecules that air consists of. Even if he is right in that case, the definitions have to work for everything and with electromagnetic waves there's nothing material to grab on to.

**Comment by alanruttenberg** [comment]
Fixed in the next release
