### ISSUE TITLE
Organizations as Object Aggregates

### ISSUE THREAD

**Issue by neilotte** [BFO-ontology/BFO-2020#19]
Given extensional mereology for object aggregates, if organizations are object aggregates, then if two organizations (x and y) have member parts at all times the same set of members, then x=y. 

Are there compelling counterexamples here?

These would need to be cases where:
- X and Y are instances of Organization.
- X and Y come to exist at the same time.
- X and Y cease to exist at the same time.
- X and Y share membership.
- X is not identical to Y.

**Comment by alanruttenberg** [comment]
On Sun, Jul 18, 2021 at 10:28 PM J. Neil Otte ***@***.***>
wrote:

> Given extensional mereology for object aggregates, if organizations are
> object aggregates, then if two organizations (x and y) have member parts at
> all times the same set of members, then x=y.
>
> Are there compelling counterexamples here?
>
> These would need to be cases where:
>
>    - X and Y are instances of Organization.
>    - X and Y come to exist at the same time.
>    - X and Y cease to exist at the same time.
>    - *At all times X and Y have the same membership.*
>    - X is not identical to Y.
>
> The text gets it right. The come and cease to exist conditions aren't the
right conditions. The condition is that they are both member parts of an
organization at exactly the same time.

**Comment by alanruttenberg** [comment]
I think this is a plausible situation other than the fact that the two
organizations are unlikely to have been created simultaneously, where it is
expected that there will be at least one person that will be at least one
member as soon as the organization exists.
Alan

**Comment by dlutz2** [comment]
Could representing organizations as object aggregates ("_exactly of a plurality of objects as member_parts_") be a case of trying to force fit an entity into an existing construct? Organizations do behave as if they have an identity that is independent of their members, to the extent that the identity of the organization can survive loss of all its members: military organizations have formal processes for deactivating and reactivating ("reflagging") units (https://history.army.mil/books/Lineage/reflag/fm.htm). In between they have no members and consist only of the unit regalia but are consider to be the same unit, with name, honors and history intact, when reactivated. Similarly, shell companies have owners (external roles) but no employees/members and still would have an identity, rights and capabilities as a legal person.

**Comment by alanruttenberg** [comment]
Says Barry: 

> The financial services industry sometimes creates 1000s of financial entities, each one of which is created to issue a single collateralized debt obligation so that if the CDO goes bankrupt no real human beings will get hurt.
> Suppose these entities needed to have say real human beings as members. 
> Many of them could be created with the same members at the same time and abandoned at the same time  
> 
> I am willing to drop 'organization' as a subclass of 'object aggregate' and work on organization later. This will just mean dropping anything like a organization from the list of examples in the ISO doument

**Comment by apetosa** [comment]
The BFO 2020 documentation considers an organization not just in terms of its member parts but of member parts that hold roles of specific types. It does not formalize a definition because Organization is a domain-specific term. In this sense Corporation X and Tennis Club Y could have the same temporally concurrent physical membership, but the roles that corporate organization members play in no way exactly coincide with those the roles engages in a tennis club organization. For this reason, a Corporate Organization universal is not the same as a Tennis Club universal.

If we have Tennis Club D & Tennis Club E, and both tennis clubs contain the same members each of whom engages in precisely the same role across both tennis clubs, these are not exactly the same tennis clubs. They are simply two instances of the Tennis Club Organization universal. Similarly, if two financial entities with the same human membership. with each member playing precisely the same role in both financial entities, concurrently stand in relation to two different collateralized debt obligations and then are concurrently abandoned, why would these two financial organizations not be considered Financial Organization instances, with, for instance, the following inheritance chain: Financial Organization "is_a(n)" Organization "is_a(n)" Object Aggregate?

BFO's "Role" definition is very clear. It is a Realizable Entity, meaning it inheres in some Independent Continuant that is not a Spatial Region and that its instances participate in some correlated process(es). Additionally, a Role can only exist if its bearer is in some non-mandatory set of circumstances (physical, social or institutional) and its cessation does not alter its bearers physical make-up. This is different than a Position. Whether within a corporate or military context, a Position, unlike a Role does not require a bearer at all times that it exists, which is why positions exist unfilled within their respective organizational structures. However, I am not quite sure how best to categorize Position in terms of BFO.

**Comment by alanruttenberg** [comment]
We will remove the examples that are close to "organization" from the member part of and object aggregate definitions. This means
- Drop *employee of an industrial company* as an example for *member part of*, 
- Replace *fire brigade* with *litter of wolf pups* as an example in Note 2 of *object aggregate*
- We are discussing whether or not to change *A symphony orchestra* as an example for *object aggregate*. Will add a comment when that is resolved.


@apetosa The question of "position" is better discussed on the bfo-discuss list. As a start you might think about position as position "on paper". In other words, the role (when occupied) is described as the documented position. It might be considered a [document act](http://ontology.buffalo.edu/smith/articles/document-acts.pdf) to fill the position by granting the role. I would like to say the document bears a realizable entity, but it's a GDC and we don't have something like that yet for GDCs. It's being discussed.

**Comment by alanruttenberg** [comment]
We will change *A symphony orchestra* as example of object aggregate to *The aggregate of the musicians in a symphony orchestra and their instruments*

**Comment by apetosa** [comment]
Would not this make a symphony orchestra a defined class formed on the union of musicians and their instruments? If so, then the meaning of Object Aggregate category is becoming more obscure. There is a highly practical need for business entities to express their organizational structures and the relationship between their “organizations” and “sub-organizations”. Many businesses that attempt to model such a structure ontologically rely on the W3C Organization Ontology (see: https://www.w3.org/TR/vocab-org/). Here is a screenshot:

 



 

Are we to consider the “subOrganizationOf” relation as a type of “continuant part of at” BFO relation, which has “Continuant” both as its domain & range values? In contrast, would not a “sub-organization” stand in a BFO “member part of at” relation with “Organization”? Is not a “sub-organization”, in part, a collective of people engaged in specific roles associated with an organization, and, hence, be considered “members” of that organization? Also, based on past discussions regarding granularity, would not a “sub-organization” be typed both as an Object and Object Aggregate, with the type reference contingent upon the granularity, and where Object & Object Aggregate are NOT asserted to be disjoint?

 

Yes, “Organization” is domain-specific, and BFO does not formally address it. However, the relational types’ intensions are critical when applied in business. Some practical guidance is appreciated. Thank you.

**Comment by alanruttenberg** [comment]
> Would not this make a symphony orchestra a defined class formed on the union of musicians and their instruments?

Yes

> If so, then the meaning of Object Aggregate category is becoming more obscure.

How so? Please refer to the documentation (definitions, examples) for object aggregate in this repository when explaining the problem.

> There is a highly practical need for business entities to express their organizational structures and the relationship between their “organizations” and “sub-organizations”. Many businesses that attempt to model such a structure ontologically rely on the W3C Organization Ontology (see: https://www.w3.org/TR/vocab-org/). Here is a screenshot: Are we to consider the “subOrganizationOf” relation as a type of “continuant part of at” BFO relation, which has “Continuant” both as its domain & range values? In contrast, would not a “sub-organization” stand in a BFO “member part of at” relation with “Organization”? Is not a “sub-organization”, in part, a collective of people engaged in specific roles associated with an organization, and, hence, be considered “members” of that organization? Also, based on past discussions regarding granularity, would not a “sub-organization” be typed both as an Object and Object Aggregate, 

This issue documents the fact that we are pulling back from suggesting that organizations are object aggregates. So no, at least if you are reasoning from previous discussions of organizations as object aggregates

> with the type reference contingent upon the granularity, and where Object & Object Aggregate are NOT asserted to be disjoint? Yes, “Organization” is domain-specific, and BFO does not formally address it. However, the relational types’ intensions are critical when applied in business. Some practical guidance is appreciated. Thank you. 

The question of how to represent organizations is outside the scope of BFO proper. Now, any implicit suggestions that BFO has a specific representation in mind for organizations has been removed. The discussion of representation of organization should be restarted, on the bfo-discuss list perhaps, without the previous assumption that they are to be represented using object aggregates. As far as them being objects, review the definition of object and causal unity and then present your reasoning about why an organization is an object.

**Comment by apetosa** [comment]
> As far as them being objects, review the definition of object and causal unity and then present your reasoning

> about why an organization is an object.

Yeah, I get it. A person is casually unified by a physical covering – skin. This qualifies a Person to be categorized as a BFO Object. If an Object Aggregate is a Material Entity exactly the plurality (>=1) of Objects as “member parts” which together form a unit and “member part of at” relates a mutually exhaustive and pairwise disjoint partition of these Objects (with the cardinality constraint noted in the definition), then why would it not follow that a collective of people Objects engaged in prescribed roles are not “member parts” of an organization, making organization an Object Aggregate?

 

There is nothing in the BFO 2020 documentation that rationalizes not extending Organization from Object Aggregate. Maybe this means BFO needs to be clearer on how it defines Object Aggregate and “member part of at”.

 

Exactly what is it about “Organization” that does NOT meet the formal definition of Object Aggregate?

 

> This issue documents the fact that we are pulling back from suggesting that organizations are object aggregates.

“Organization”, which essentially is one step removed from BFO categories, is highly important to so many. In the interest of businesses and other stakeholders not walking away from BFO altogether, I think answering this question is worthwhile.

**Comment by alanruttenberg** [comment]
>  Exactly what is it about “Organization” that does NOT meet the formal definition of Object Aggregate?

The issue occurs when an organization has organizations as member parts, for instance the HR department of a company. Recall that all of the members must not overlap. Now add another sub-organization such as a committee, one of whose members is in the HR department. The sub-organizations are now objects and object aggregates. Object aggregates because that's the assumption here, and objects because of the domain of member-part-of.  Object and object aggregate are not disjoint, that decision still a source of disagreements. But because they aren't disjoint, so far everything is OK. However, the two sub-organizations overlap, the overlap being that person who is both in HR and the committee. But all the member parts must not overlap according to the definition of member part of. So we now have an inconsistency.

There is some related discussion in this issue: https://github.com/CommonCoreOntology/CommonCoreOntologies/issues/102
